apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test     # (!) required
    apps.tanzu.vmware.com/language: java      # tap1.3 multi-pipeline functionality
spec:
  params:
    - name: source-url                       # (!) required
    - name: source-revision                  # (!) required
    - name: testing-sub-path
      default: ""
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: testing-sub-path
          value: $(params.testing-sub-path)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
          - name: testing-sub-path
        steps:
          - name: test
            image: maven:3.8.5-openjdk-18-slim
            script: |-
              cd `mktemp -d`

              curl -SL $(params.source-url) | tar xvzf -
              if [ ! -z "$(params.testing-sub-path)" ]; then
                if [ -d "$(params.testing-sub-path)" ]; then
                  echo "navigating to repo subpath $(params.testing-sub-path)"
                  cd $(params.testing-sub-path)
                else
                  echo "repo subpath $(params.testing-sub-path) does not exists. skipping subpath..."
                fi
              fi
              mvn test